<template>
  <div class="home">
    <h1>This is the home page</h1>
    <!-- <HelloWorld msg="Welcome to Your Vue.js + TypeScript App"/> -->
    <p>Tellus auctor habitasse lectus sit justo porta nascetur potenti. Tincidunt facilisi commodo lacus aptent. Purus mattis id platea molestie euismod interdum? Hac posuere primis eros hac nibh lacus. Consequat mi dui vitae libero ligula platea. Ligula odio donec dapibus pretium dis in cum dictumst. In hendrerit nulla magnis lacinia nisi aenean tempus mi, condimentum hac rutrum. Facilisis euismod ullamcorper cursus facilisis habitasse litora ornare facilisi. Nunc nibh purus natoque odio nunc.</p>
    <p>Potenti elit fringilla rutrum. Placerat ac congue sodales tempor nullam duis proin in vestibulum gravida mi. Integer penatibus conubia faucibus auctor congue velit morbi varius tempus. Nulla lacus massa lectus vestibulum phasellus euismod a magnis faucibus scelerisque non commodo. Sit quis class rutrum placerat morbi mi phasellus vehicula, mus ultricies aenean potenti. Odio ultrices ac ultrices ligula. Placerat in pulvinar vestibulum blandit auctor consectetur mus tempor. Mi ridiculus scelerisque sodales enim cum et vehicula.</p>
    <p>Porta sapien id fermentum rhoncus accumsan orci mauris taciti sociis. Pretium nec et volutpat mauris nibh massa lacinia. Ridiculus semper ligula vivamus est praesent porttitor consequat habitant. Nullam adipiscing, nec tincidunt elit aenean. Fermentum ad eu vestibulum; aenean aliquet cursus aliquet faucibus. Senectus eget, erat ligula justo? Ultricies auctor rhoncus urna, dignissim nostra scelerisque. Laoreet netus ornare semper donec sit. Sagittis magna sollicitudin senectus natoque quisque torquent.</p>
    <p>Dolor nisl consectetur parturient hendrerit nascetur ullamcorper sociosqu. Donec sem scelerisque sed class nisi lorem, magnis tincidunt convallis commodo faucibus. Euismod eget purus, dignissim faucibus. Eu porta diam posuere pellentesque natoque mus quam. Quis ipsum curabitur tortor taciti vivamus volutpat ultrices. In dictum mi gravida purus! Platea aliquam aliquam maecenas rhoncus faucibus augue sed fusce, ultricies consequat. Ligula vitae placerat fusce himenaeos interdum maecenas potenti.</p>
    <p>Consequat cubilia nisl dapibus parturient nisi, ligula facilisi dis commodo. Nibh suscipit; tempus nostra platea et euismod. Aenean donec nostra facilisi nisi sollicitudin laoreet eleifend aptent amet rhoncus quis vulputate. Vitae mus nisl taciti ultrices viverra mattis nisi porta rhoncus molestie eleifend elementum? Aliquet etiam ridiculus parturient habitasse lectus pellentesque. Condimentum inceptos gravida scelerisque vehicula torquent ultrices montes, dis placerat accumsan cursus. Imperdiet dapibus natoque pulvinar laoreet lacinia commodo leo. Eu felis felis tellus ultricies molestie morbi. Luctus cubilia diam dapibus varius fames mollis condimentum vivamus ornare condimentum augue rhoncus. Rutrum semper hac curabitur vivamus dictumst gravida ullamcorper?</p>    <p>Tellus auctor habitasse lectus sit justo porta nascetur potenti. Tincidunt facilisi commodo lacus aptent. Purus mattis id platea molestie euismod interdum? Hac posuere primis eros hac nibh lacus. Consequat mi dui vitae libero ligula platea. Ligula odio donec dapibus pretium dis in cum dictumst. In hendrerit nulla magnis lacinia nisi aenean tempus mi, condimentum hac rutrum. Facilisis euismod ullamcorper cursus facilisis habitasse litora ornare facilisi. Nunc nibh purus natoque odio nunc.</p>
    <p>Potenti elit fringilla rutrum. Placerat ac congue sodales tempor nullam duis proin in vestibulum gravida mi. Integer penatibus conubia faucibus auctor congue velit morbi varius tempus. Nulla lacus massa lectus vestibulum phasellus euismod a magnis faucibus scelerisque non commodo. Sit quis class rutrum placerat morbi mi phasellus vehicula, mus ultricies aenean potenti. Odio ultrices ac ultrices ligula. Placerat in pulvinar vestibulum blandit auctor consectetur mus tempor. Mi ridiculus scelerisque sodales enim cum et vehicula.</p>
    <p>Porta sapien id fermentum rhoncus accumsan orci mauris taciti sociis. Pretium nec et volutpat mauris nibh massa lacinia. Ridiculus semper ligula vivamus est praesent porttitor consequat habitant. Nullam adipiscing, nec tincidunt elit aenean. Fermentum ad eu vestibulum; aenean aliquet cursus aliquet faucibus. Senectus eget, erat ligula justo? Ultricies auctor rhoncus urna, dignissim nostra scelerisque. Laoreet netus ornare semper donec sit. Sagittis magna sollicitudin senectus natoque quisque torquent.</p>
    <p>Dolor nisl consectetur parturient hendrerit nascetur ullamcorper sociosqu. Donec sem scelerisque sed class nisi lorem, magnis tincidunt convallis commodo faucibus. Euismod eget purus, dignissim faucibus. Eu porta diam posuere pellentesque natoque mus quam. Quis ipsum curabitur tortor taciti vivamus volutpat ultrices. In dictum mi gravida purus! Platea aliquam aliquam maecenas rhoncus faucibus augue sed fusce, ultricies consequat. Ligula vitae placerat fusce himenaeos interdum maecenas potenti.</p>
    <p>Consequat cubilia nisl dapibus parturient nisi, ligula facilisi dis commodo. Nibh suscipit; tempus nostra platea et euismod. Aenean donec nostra facilisi nisi sollicitudin laoreet eleifend aptent amet rhoncus quis vulputate. Vitae mus nisl taciti ultrices viverra mattis nisi porta rhoncus molestie eleifend elementum? Aliquet etiam ridiculus parturient habitasse lectus pellentesque. Condimentum inceptos gravida scelerisque vehicula torquent ultrices montes, dis placerat accumsan cursus. Imperdiet dapibus natoque pulvinar laoreet lacinia commodo leo. Eu felis felis tellus ultricies molestie morbi. Luctus cubilia diam dapibus varius fames mollis condimentum vivamus ornare condimentum augue rhoncus. Rutrum semper hac curabitur vivamus dictumst gravida ullamcorper?</p>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import HelloWorld from '@/components/HelloWorld.vue'; // @ is an alias to /src

@Component({
  components: {
    HelloWorld,
  },
})
export default class Home extends Vue {}
</script>
